name: Android Build and Release

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [ 'master' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract version from tag
        if: startsWith(github.ref, 'refs/tags/')
        id: extract-version
        run: |
          # 获取标签名（去掉 'v' 前缀）
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          VERSION_NAME="${TAG_NAME//v/}"
          
          # 计算版本号（基于提交历史）
          VERSION_CODE=$(git rev-list --count HEAD)
          
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV
          echo "VERSION_CODE=$VERSION_CODE" >> $GITHUB_ENV
          echo "Extracted version: $VERSION_NAME ($VERSION_CODE)"

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # 生成密钥文件在项目根目录
      - name: Restore Keystore
        run: |
          KEYSTORE_PATH="$GITHUB_WORKSPACE/release.keystore"
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > "$KEYSTORE_PATH"
          echo "密钥文件位置: $KEYSTORE_PATH"
          ls -la "$(dirname $KEYSTORE_PATH)"
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

      # 设置绝对路径环境变量
      - name: Setup signing variables
        run: |
          KEYSTORE_PATH="$GITHUB_WORKSPACE/release.keystore"
          echo "RELEASE_STORE_FILE=$KEYSTORE_PATH" >> $GITHUB_ENV
          echo "RELEASE_STORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> $GITHUB_ENV
          echo "RELEASE_KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> $GITHUB_ENV
          echo "RELEASE_KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> $GITHUB_ENV

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Verify keystore exists
        run: |
          echo "检查密钥文件是否存在..."
          ls -la "$GITHUB_WORKSPACE"
          if [ -f "$GITHUB_WORKSPACE/release.keystore" ]; then
            echo "✅ 找到 release.keystore 文件"
            echo "文件大小: $(du -h $GITHUB_WORKSPACE/release.keystore | cut -f1)"
          else
            echo "❌ 错误：release.keystore 文件不存在！"
            exit 1
          fi

      - name: Build Release APK
        run: ./gradlew assembleRelease --stacktrace
        env:
          ORG_GRADLE_PROJECT_RELEASE_STORE_FILE: ${{ env.RELEASE_STORE_FILE }}
          ORG_GRADLE_PROJECT_RELEASE_STORE_PASSWORD: ${{ env.RELEASE_STORE_PASSWORD }}
          ORG_GRADLE_PROJECT_RELEASE_KEY_ALIAS: ${{ env.RELEASE_KEY_ALIAS }}
          ORG_GRADLE_PROJECT_RELEASE_KEY_PASSWORD: ${{ env.RELEASE_KEY_PASSWORD }}
          VERSION_CODE: ${{ env.VERSION_CODE }}
          VERSION_NAME: ${{ env.VERSION_NAME }}

      - name: Upload APK to Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: app/build/outputs/apk/release/*.apk
          generate_release_notes: true
          body: |
            ### 本次更新内容
            - 修复了构建签名路径问题
            - 优化了 CI 工作流配置